apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-service-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tea-service
      version: v2
  template:
    metadata:
      labels:
        app: tea-service
        version: v2
    spec:
      containers:
      - name: tea-service
        image: muratzorer/tea-service:2.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tea-service
spec:
  host: tea-service
  subsets:
  - name: v2
    labels:
      version: v2
---
  apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: tea-service
  spec:
    hosts:
    - tea-service
    http:
    - route:
      - destination:
          host: tea-service
          subset: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api
spec:
  hosts:
  - "*"
  gateways:
  - api-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /tea
    - uri:
        prefix: /actuator
    route:
    - destination:
        host: tea-service
        subset: v2
    timeout: 10s
