server:
  port: 9080
  
build:
  version: '@project.version@'
  timestamp: '@maven.build.timestamp@'
  
spring:
  application:
    name: '@project.artifactId@'
  sleuth:
    propagation-keys:
    - x-request-id
    - x-ot-span-context
    
# serves enabled actuator endpoints    
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics