apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "foo-service-require-jwt"
spec:
  targets:
  - name: foo-service
  origins:
  - jwt:
      issuer: "www.muratcavus.com"
      jwksUri: "http://10.184.29.32:9080/public/well-known/jwks.json"
      triggerRules:
      - excludedPaths:
        - exact: /foo-service/health
  principalBinding: USE_ORIGIN
