apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: foo-service-full-access
  namespace: tutorial
spec:
  rules:
  - services: ["muhtar.tutorial.svc.cluster.local"]
    methods: ["POST"]
    paths: ["/concentrationWS/*"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: foo-service-binding
  namespace: tutorial
spec:
  subjects:
  - properties:
      request.auth.claims[iss]: "www.muratcavus.com"
  roleRef:
    kind: ServiceRole
    name: "foo-service-full-access"
